spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stu_mng?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jdbc:
    template:
      query-timeout: 3


mybatis-plus:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#  开启驼峰命名规则
  configuration:
    map-underscore-to-camel-case: true